"""RawTherapee processing profile. An INI file, not XMP at all.

RawTherapee keeps its settings in a `.pp3`, which is a plain INI document. Its
sliders use different ranges from Adobe's -- exposure compensation is in stops,
but Contrast and Saturation run -100..100 with a different response curve --
so the values are mapped rather than copied.

**Not verified against a real RawTherapee installation.** The key names follow
the documented profile format.
"""

from __future__ import annotations

from pathlib import Path


def to_pp3(recipe) -> str:
    g = recipe.global_adjustments
    lines = [
        "[Version]",
        "AppVersion=5.9",
        "Version=346",
        "",
        "[Exposure]",
        "Auto=false",
        f"Compensation={g.exposure_ev:.2f}",
        f"Contrast={g.contrast}",
        f"Saturation={g.saturation}",
        f"Black={int(g.blacks * 0.6)}",
        f"HighlightCompr={max(0, -g.highlights)}",
        f"ShadowCompr={max(0, g.shadows)}",
        "",
        "[Directional Pyramid Denoising]",
        f"Enabled={'true' if recipe.detail.denoise_luminance else 'false'}",
        f"Luma={recipe.detail.denoise_luminance}",
        f"Chroma={recipe.detail.denoise_color}",
        "",
        "[Sharpening]",
        f"Enabled={'true' if recipe.detail.sharpening else 'false'}",
        f"Amount={recipe.detail.sharpening}",
        "",
        "[Black & White]",
        f"Enabled={'true' if recipe.color.monochrome else 'false'}",
        "",
        "[Rotation]",
        f"Degree={recipe.geometry.rotation_deg if not recipe.geometry.preserve_existing_tilt else 0.0}",
        "",
        "# Generated by photo-ai-toolkit as a suggestion.",
        f"# intent: {recipe.intent}",
        f"# source checksum: {recipe.source_checksum}",
    ]
    for item in recipe.preserve:
        lines.append(f"# preserve: {item}")
    return "\n".join(lines) + "\n"


def write_suggestion(recipe, root: Path) -> Path:
    from photoai.edit_schema import suggestion_path

    path = suggestion_path(root, recipe.asset_id or "unknown", recipe.variant, ".pp3")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_pp3(recipe), encoding="utf-8")
    return path
