#!/bin/sh
# Generated by photo-ai-toolkit. Review contact_sheet_delete.jpg first.
#
# This script contains no filenames. The list lives in delete_plan.json beside
# it and is carried out by Python, which moves each file to the Trash after
# checking its checksum still matches. Nothing is deleted permanently, and a
# filename can never be interpreted as a command.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
exec /Users/vitaliikarasov/Desktop/photo-ai-toolkit/.venv/bin/python /Users/vitaliikarasov/Desktop/photo-ai-toolkit/cli.py trash --plan "$HERE/delete_plan.json" --apply
